# Generated by Django 4.2.9 on 2024-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="role",
            field=models.IntegerField(
                choices=[(1, "总监"), (2, "经理"), (3, "员工")],
                default=3,
                verbose_name="role",
            ),
        ),
    ]
