# Generated by Django 4.2.9 on 2024-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="depart")),
                ("order", models.IntegerField(verbose_name="顺序")),
                ("count", models.IntegerField(verbose_name="人数")),
            ],
        ),
    ]
