# Generated by Django 4.2.9 on 2024-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstday", "0002_department_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo", name="age", field=models.IntegerField(default=2),
        ),
    ]
