# Generated by Django 4.2.9 on 2024-03-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firstday", "0003_alter_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="账户余额"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(default=0, verbose_name="入职时间"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="firstday.department",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别 "
            ),
        ),
    ]
