# Generated by Django 4.2.9 on 2024-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstday", "0004_userinfo_account_userinfo_create_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo", old_name="account", new_name="account_salary",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(verbose_name="入职时间"),
        ),
    ]
